# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yel-yaqi <yel-yaqi@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/29 11:30:11 by yel-yaqi          #+#    #+#              #
#    Updated: 2024/08/30 16:59:09 by yel-yaqi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CFLAGS = -Wall -Wextra -Werror -std=c++98

TARGET = megaphone

$(TARGET): megaphone.cpp Makefile
	c++ megaphone.cpp $(CFLAGS) -o $@

clear:
	rm -f megaphone